---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_repository_module.html
- name: Add Nomad repo
  yum_repository:
    name: nomad
    description: Hashicorp repo voor nomad
    baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Install Nomad
  yum:
    name: nomad
    state: installed
  notify: restart nomad

#https://docs.ansible.com/ansible/2.4/lineinfile_module.html
#- name: nomadbindaddress
 # lineinfile:
  #  path: /tmp/testfile
   # line: '192.168.1.99 foo.lab.net foo'
- name: nomadBindaddr
  lineinfile:
    path: /etc/nomad.d/nomad.hcl
    regexp: '^bind_addr'
    line: 'bind_addr = "{{ GetInterfaceIP \\"eth1\\" }}"'
