---
- name: Add nomad repository.
  get_url:
    url: "{{ nomad_yum_repo_url }}"
    dest: '/etc/yum.repos.d/nomad-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install nomad.
  package:
    name: "{{ nomad_package }}"
    state: "{{ nomad_package_state }}"
  notify: restart nomad

- name: Template nomad
  template:
     src: nomad.hcl.j2
     dest:  /etc/nomad.d/nomad.hcl
  notify: restart nomad

- name: Template alertmanager
  template:
    src: alertmanager.hcl.j2
    dest:  /home/alertmanager.hcl

- name: Template grafana
  template:
    src: grafana.hcl.j2
    dest:  /home/grafana.hcl

# - name: Template prometheus
#   template:
#     src: prometheus.hcl.j2
#     dest:  /etc/nomad.d/prometheus.hcl


