---
- name: Add nomad repository.
  get_url:
    url: "{{ nomad_yum_repo_url }}"
    dest: '/etc/yum.repos.d/nomad-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install nomad.
  package:
    name: "{{ nomad_package }}"
    state: "{{ nomad_package_state }}"
  notify: enable nomad

- name: nomadAdvertise
  lineinfile:
    path: /etc/nomad.d/nomad.hcl
    line: |-
      advertise {
        http = "192.168.1.4"
        rpc = "192.168.1.4"
        serf = "192.168.1.4"
      }
  notify: restart nomad

# Bindaddr zorgde ervool dat nomad ui NIET werkte
# - name: nomadBindaddr 
#   replace:
#     path: /etc/nomad.d/nomad.hcl
#     regexp: "{{ nomad_bindaddreplace }}" 
#     replace: "{{ nomad_bindaddr }}" 
#   notify: restart nomad

# - name: nomad 127.0.0.1 connection refused
#   shell: export NOMAD_ADDR=http://192.168.1.4:4646
