# https://github.com/geerlingguy/ansible-role-docker/tree/master/tasks
---
docker_package: "docker-ce"
docker_package_state: present

docker_service_state: started
docker_service_enabled: true

docker_yum_repo_url: https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-ce.repo
docker_yum_gpg_key: https://download.docker.com/linux/centos/gpg