---
- name: Copy grafana.hcl
  copy:
    src: templates/grafana.hcl.j2
    dest: /home/grafana.hcl
    owner: root
    group: wheel
    mode: 0644

- name: Copy alaertmanager.hcl
  copy:
    src: templates/alertmanager.hcl.j2
    dest: /home/alertmanager.hcl
    owner: root
    group: wheel
    mode: 0644

- name: Copy prometheus.hcl
  copy:
    src: templates/prometheus.hcl.j2
    dest: /home/prometheus.hcl
    owner: root
    group: wheel
    mode: 0644

- name: Copy tomcat.hcl
  copy:
    src: templates/tomcat.hcl.j2
    dest: /home/tomcat.hcl
    owner: root
    group: wheel
    mode: 0644

# nomad job run /home/tomcat.hcl
- name: start nomad jobs 
  shell: |-
    nomad job run /home/prometheus.hcl 
    nomad job run /home/grafana.hcl
    nomad job run /home/alertmanager.hcl


