---
- name: Add nomad repository
  get_url:
    url: "{{ nomad_yum_repo_url }}"
    dest: '/etc/yum.repos.d/nomad-ce.repo'
    owner: root
    group: root
    mode: 0644

- name: Install nomad
  package:
    name: "{{ nomad_package }}"
    state: "{{ nomad_package_state }}"
  notify: enable nomad

- name: nomadBindaddr
  replace:
    path: /etc/nomad.d/nomad.hcl
    regexp: "{{ nomad_bindaddreplace }}" 
    replace: "{{ nomad_bindaddr }}" 

- name: nomadServerAddr
  lineinfile:
    path: /etc/nomad.d/nomad.hcl
    regexp: "{{ nomad_serveraddrreplace }}"
    line: "{{ nomad_serveraddr }}"

# Multi line configuratie
- name: nomadNotServer
  replace:
    path: /etc/nomad.d/nomad.hcl
    regexp: |-
      server {
        enabled = true
    replace: |-
      server {
        enabled = false
  notify: restart nomad